app/controllers/DashboardController.php
<?php

namespace app\controllers;

use app\models\Anomaly;
use app\models\EveType;
use app\models\forms\SystemSearch;
use app\models\Planet;
use app\models\StaticWH;
use app\models\System;
use app\models\ZKill;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class DashboardController extends Controller
{
    public function actionIndex()
    {
        $now = time();
        $kills = ZKill::find()
            ->joinWith(['system'])
            ->where(['>', 'time', ($now - 86400 * 7)])
            ->orderBy('`time` DESC')->all();
        $weeklyChart = [];
        $datesWeek = [];
        for($i = ($now - 86400 * 7); $i <= $now; $i += 3600) {
            $dtWeek = date('d M', $i);
            $datesWeek[$dtWeek] = $dtWeek;
            $weeklyChart[$dtWeek] = 0;
        }

        foreach($kills as $kill) {
            /** @var $kill ZKill */
            $dtWeek = date('d M', $kill->time);
            $weeklyChart[$dtWeek] += 1;
        }

        $randomSystem = System::find()->orderBy('RAND()')->limit(1)->one();
        $randomSystems = System::find()->orderBy('RAND()')->limit(5)->all();

        return $this->render('index', [
            'weeklyChart' => array_values($weeklyChart),
            'datesWeek' => array_values($datesWeek),
            'randomSystem' => $randomSystem,
            'randomSystems' => $randomSystems,
        ]);
    }

    public function actionSystem($title) {
        $system = System::getByName($title);
        if(!$system) {
            throw new NotFoundHttpException('Specified system not found!');
        }
        /** @var $system System */

        $anomalyList = [];
        foreach($system->anomalies as $anomaly) {
            $anomalyList[$anomaly->type][] = $anomaly;
        }

        $now = time();
        $kills = ZKill::find()
            ->joinWith(['system'])
            ->where(['system_id' => $system->external_id])
            ->andWhere(['>', 'time', ($now - 86400 * 7)])
            ->orderBy('`time` DESC')->all();
        $weeklyChart = [];
        $dailyChart = [];
        $datesWeek = [];
        $datesDay = [];
        for ($i = ($now - 86400 * 7); $i <= $now; $i += 3600) {
            $dtWeek = date('d M', $i);
            $dtDay = date('d.m.y H:00', $i);
            $datesWeek[$dtWeek] = $dtWeek;
            $datesDay[$dtDay] = $dtDay;
            $weeklyChart[$dtWeek] = 0;
            $dailyChart[$dtDay] = 0;
        }

        foreach ($kills as $kill) {
            /** @var $kill ZKill */
            $dtWeek = date('d M', $kill->time);
            $dtDay = date('d.m.y H:00', $kill->time);

            $weeklyChart[$dtWeek] += 1;
            $dailyChart[$dtDay] += 1;
        }

        $latestKills = ZKill::find()
            ->where(['system_id' => $system->external_id])
            ->orderBy('`time` DESC')
            ->andWhere(['>', 'time', ($now - 86400 * 30)])
            ->limit(10)
            ->all();

        $typeIds = [];
        foreach ($latestKills as $kill) {
            $typeIds[] = $kill->victim->ship_type_id;
            $typeIds[] = $kill->attacker->ship_type_id;
        }
        $shipTypes = EveType::find()->where(['id' => $typeIds])->indexBy('id')->all();

        $planetInfo = [];
        $planets = ArrayHelper::getValue($system->getCcpObject(), 'planets', []);
        foreach ($planets as $p) {
            $planet = null;
            $attempt = 0;
            do {
                try {
                    $planet = Planet::findOne($p['planet_id']);
                } catch (\Throwable $e) {
                    Yii::error($e);
                    usleep(300);
                }
                $attempt++;
            } while (!($planet instanceof Planet) && $attempt < 3);

            if ($planet instanceof Planet) {
                $planetInfo[] = $planet;
            }
        }

        return $this->render('system', [
            'system' => $system,
            'anomalyList' => $anomalyList,
            'planets' => $planetInfo,
            // EVE kills chart
            'weeklyChart' => array_values($weeklyChart),
            'dailyChart' => array_values($dailyChart),
            'datesWeek' => array_values($datesWeek),
            'datesDay' => array_values($datesDay),
            'latestKills' => $latestKills,
            'killsShipTypes' => $shipTypes,
        ]);
    }

    public function actionAutocomplete()
    {
        if (!\Yii::$app->request->isAjax) {
            throw new BadRequestHttpException('Bad request');
        }

        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $term = \Yii::$app->request->get('term', '');
        return \app\models\System::find()
            ->select(['`title` AS value', '`title` AS label'])
            ->where(['LIKE', 'title', $term])
            ->limit(15)
            ->asArray()
            ->all();
    }

    public function actionAnomaly($id)
    {
        $anomaly = Anomaly::findOne($id);
        if(!$anomaly) {
            throw new NotFoundHttpException('Anomaly type not found');
        }

        return $this->render('anomaly', [
            'anomaly' => $anomaly,
        ]);
    }

    public function actionStatic($title)
    {
        $static = StaticWH::find()->where(['title' => $title])->one();
        if(!$static) {
            throw new NotFoundHttpException('Static type not found');
        }

        return $this->render('static', [
            'static' => $static,
        ]);
    }

    public function actionSearch()
    {
        if(\Yii::$app->request->isPost) {
            $model = new SystemSearch();
            if($model->load(\Yii::$app->request->post())) {
                if($model->validate()) {
                    $system = $model->getSystem();
                    $this->redirect('/system/'.$system->title);
                }
            }
        }
        else {
            throw new BadRequestHttpException('Bad request');
        }
    }

}

app/views/layouts/_search_form.php
<?php

/* @var $this \yii\web\View */

use yii\bootstrap\ActiveForm;
use yii\jui\AutoComplete;

$model = new \app\models\forms\SystemSearch();
$form = ActiveForm::begin([
    'action' => ['/dashboard/search'],
    'options' => [
        'class' => 'system-search-form',
        'enctype' => 'multipart/form-data',
    ],
    'fieldConfig' => [
        'options' => [
            //'tag' => false,
            'showErrors' => false,
            'showHints' => false,
        ],
        'template' => "{input}",
    ],
    'enableClientValidation' => false,
]) ?>
    <div class="input-wrap">
        <span>System:</span><?= $form->field($model, 'title')->widget(
            AutoComplete::className(), [
            'clientOptions' => [
                'source' => \yii\helpers\Url::to('/dashboard/autocomplete'),
                'select' => new \yii\web\JsExpression('function( event, ui ) {
                    $(".autocomplete-system-search").val(ui.item.label);
                    $(".system-search-form").submit();
                    return false;
                }'),
            ],
            'options' => [
                'class' => 'autocomplete-system-search'
            ]
        ]);
        ?><!--input type="submit" value="Go"-->
    </div>
<?php ActiveForm::end(); ?>
<?php
    $js = "
        $('.autocomplete-system-search').keyup(function () {
            var offset = $(this).offset();
            $('ul.ui-autocomplete').css('top', (offset.top + 18) + 'px');
            $('ul.ui-autocomplete').css('left', offset.left + 'px');
        });
    ";
    $this->registerJs($js);
?>

app/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\helpers\Html;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <?php if(!YII_ENV_DEV) :?>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-110147905-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-110147905-1');
        </script>
        <!-- Yandex.Metrika counter -->
        <script type="text/javascript" >
            (function (d, w, c) {
                (w[c] = w[c] || []).push(function() {
                    try {
                        w.yaCounter46873422 = new Ya.Metrika({
                            id:46873422,
                            clickmap:true,
                            trackLinks:true,
                            accurateTrackBounce:true,
                            webvisor:true
                        });
                    } catch(e) { }
                });

                var n = d.getElementsByTagName("script")[0],
                    s = d.createElement("script"),
                    f = function () { n.parentNode.insertBefore(s, n); };
                s.type = "text/javascript";
                s.async = true;
                s.src = "https://mc.yandex.ru/metrika/watch.js";

                if (w.opera == "[object Opera]") {
                    d.addEventListener("DOMContentLoaded", f, false);
                } else { f(); }
            })(document, window, "yandex_metrika_callbacks");
        </script>
        <noscript><div><img src="https://mc.yandex.ru/watch/46873422" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
        <!-- /Yandex.Metrika counter -->
    <?php endif; ?>
    <meta charset="<?= Yii::$app->charset ?>" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="yandex-verification" content="efde8408ef359f7b" />
    <link rel="shortcut icon" href="/favicon.png" type="image/png" />
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="container whscan-main">

    <header class="header">
        <a href="/">
            <img src="/images/logo.png" />
            <span class="red-string">W</span>
            <span class="title1">ormhole</span>
            <span class="title2">scanner</span>
        </a>

        <?= $this->render('_search_form'); ?>
    </header><!-- .header-->

    <div class="wrap">

        <?= Alert::widget() ?>
        <?= $content ?>

    </div>

    <footer class="footer">
        <div class="footer-container">
            <p>© 2014 - <?=date('Y') ?> WH SCANNER</p>
        </div>
    </footer>

</div>

<?php echo \app\modules\notifications\widgets\NotificationWidget::widget() ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>